---
- name: Instalar htop compatível com o sistema
  hosts: all
  become: yes
  tasks:
    - name: Habilitar repositório EPEL (caso necessário)
      yum:
        name: epel-release
        state: present

    - name: Atualizar cache do dnf
      dnf:
        update_cache: yes

    - name: Instalar htop
      dnf:
        name: htop
        state: present
