---
- name: Instalação de arquivo a partir de projeto no GitHub
  hosts: all
  become: yes
  vars:
    repositorio_git: "https://github.com/Redeley/ansible-playbooks.git"
    destino_clone: "/opt/ansible-playbook"
    arquivo_para_instalar: "klnagent64_13.2.2-1263_amd64.deb"

  tasks:
    - name: Instalar dependência do Git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clonar o repositório do GitHub
      git:
        repo: "{{ repositorio_git }}"
        dest: "{{ destino_clone }}"
        version: Redeley-patch-1
        force: yes

    - name: Tornar o arquivo executável (se necessário)
      file:
        path: "{{ destino_clone }}/{{ arquivo_para_instalar }}"
        mode: '0755'
        state: file

    - name: Executar o script ou instalar o arquivo
      command: "{{ destino_clone }}/{{ arquivo_para_instalar }}"
