---
- name: Instalar pacote .deb a partir de repositório Git
  hosts: all
  become: true
  vars:
    repo_url: "https://github.com/Redeley/ansible-playbooks.git"
    local_clone_dir: "/tmp/ansible-playbooks"
    deb_filename: "klnagent64_13.2.2-1263_amd64.deb"
    remote_dest: "/tmp/ansible-playbooks/klnagent64_13.2.2-1263_amd64.deb"

  tasks:
    - name: Clonar repositório contendo o .deb
      git:
        repo: "{{ repo_url }}"
        dest: "{{ local_clone_dir }}"
        version: "Redeley-patch-1"
        force: yes

    - name: Instalar pacote .deb
      apt:
        deb: "{{ remote_dest }}"
        state: present
    
    - name: Executar script postinstall.pl com entradas simuladas
      shell: |
        echo -e "y\n172.40.0.3\n14000\n13000\ny\n2" | perl /opt/kaspersky/klnagent64/lib/bin/setup/postinstall.pl

    - name: Executar klmover com endereço especificado
      shell: |
        cd /opt/kaspersky/klnagent64/bin && ./klmover -address 172.40.0.3

    - name: Reiniciar o serviço klnagent64
      systemd:
        name: klnagent64
        state: restarted
        enabled: true

    - name: Verificar status do serviço klnagent64
      shell: systemctl status klnagent64 --no-pager
      register: status_output

    - name: Exibir status do serviço klnagent64
      debug:
        var: status_output.stdout_lines
