---
- name: Instalar htop em máquinas Linux
  hosts: all
  become: yes
  tasks:
    - name: Garantir que o htop esteja instalado
      ansible.builtin.package:
        name: htop
        state: present


