---
- name: Atualizar apontamento do Kaspersky Network Agent via klmover no Linux
  hosts: all
  become: yes
  vars:
    ip_do_servidor_antivirus: "172.40.0.3"

  tasks:
    - name: Executar comando klmover com endereço
      ansible.builtin.command: ./klmover -address 172.40.0.3
      args:
        chdir: /opt/kaspersky/klnagent64/bin/
