---
- name: Executar klmover em máquina Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Executar comando klmover com endereço específico
      ansible.builtin.command: ./klmover -address 172.40.0.3
      args:
        chdir: /opt/kaspersky/klnagent64/bin/
      register: resultado_klmover
      failed_when: resultado_klmover.rc != 0
      changed_when: false

    - name: Mostrar saída padrão
      debug:
        var: resultado_klmover.stdout

    - name: Mostrar erro padrão (stderr)
      debug:
        var: resultado_klmover.stderr

    - name: Mostrar código de retorno
      debug:
        var: resultado_klmover.rc
