---
- name: Executar postinstall.sh nas máquinas do inventário
  hosts: all
  become: true
  vars:
    repo_url: "https://github.com/Redeley/ansible-playbooks.git"
    repo_branch: "Redeley-patch-1"
    repo_dest: "/tmp/postinstall_repo"
    script_src: "/tmp/postinstall_repo/postinstall.sh"
    script_dest: "/tmp/postinstall.sh"

  tasks:
    - name: Garantir que o Git esteja instalado
      package:
        name: git
        state: present

    - name: Clonar o repositório com o script da branch correta
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ repo_branch }}"
        force: yes

    - name: Copiar o script postinstall.sh para /tmp/
      copy:
        remote_src: true
        src: "{{ script_src }}"
        dest: "{{ script_dest }}"
        mode: '0755'

    - name: Executar o script postinstall.sh em /tmp
      command: ./postinstall.sh
      args:
        chdir: "/tmp"
