---
- name: Instalar pacote .deb a partir de repositório Git e executar script de pós-instalação
  hosts: all
  become: true
  gather_facts: yes

  vars:
    # Configurações do repositório
    repo_url: "https://github.com/Redeley/ansible-playbooks.git"
    repo_branch: "Redeley-patch-1"

    # Arquivo .deb
    deb_filename: "klnagent64_13.2.2-1263_amd64.deb"
    local_clone_base: "/tmp/ansible-playbooks"
    remote_deb_dest: "/tmp/{{ deb_filename }}"

    # Script de pós-instalação
    script_filename: "instala_postinstall.sh"
    repo_remote_clone: "/tmp/postinstall_repo"
    script_src_path: "{{ repo_remote_clone }}/{{ script_filename }}"
    script_dest_path: "/tmp/{{ script_filename }}"

  tasks:
    - name: Criar diretório de clone único localmente (localhost)
      set_fact:
        local_clone_dir: "{{ local_clone_base }}_{{ ansible_date_time.epoch }}_{{ inventory_hostname }}"
      delegate_to: localhost
      become: false

    - name: Garantir que o diretório local não exista antes de clonar
      file:
        path: "{{ local_clone_dir }}"
        state: absent
      delegate_to: localhost
      become: false

    - name: Clonar repositório contendo o .deb no localhost
      git:
        repo: "{{ repo_url }}"
        dest: "{{ local_clone_dir }}"
        version: "{{ repo_branch }}"
        force: yes
      delegate_to: localhost
      become: false

    - name: Verificar se o arquivo .deb existe no localhost antes de copiar
      stat:
        path: "{{ local_clone_dir }}/{{ deb_filename }}"
      register: deb_local_check
      delegate_to: localhost
      become: false

    - name: Abortar se o .deb não existir no localhost
      fail:
        msg: "Arquivo {{ deb_filename }} não encontrado em {{ local_clone_dir }}"
      when: not deb_local_check.stat.exists
      delegate_to: localhost
      become: false

    - name: Copiar o arquivo .deb do localhost para o host remoto
      copy:
        src: "{{ local_clone_dir }}/{{ deb_filename }}"
        dest: "{{ remote_deb_dest }}"
        mode: '0644'
      delegate_to: localhost
      become: false

    - name: Tentar instalar o pacote .deb (ignorar erro se versão mais nova já instalada)
      apt:
        deb: "{{ remote_deb_dest }}"
        state: present
      register: deb_install_result
      ignore_errors: true

    - name: Verificar se erro foi por versão mais recente
      debug:
        msg: "Versão mais nova já está instalada. Ignorando instalação."
      when: deb_install_result is failed and "'already installed' in deb_install_result.msg or 'later version' in deb_install_result.msg"

    - name: Abortar para outros erros
      fail:
        msg: "{{ deb_install_result.msg }}"
      when: deb_install_result is failed and "'already installed' not in deb_install_result.msg and 'later version' not in deb_install_result.msg"

    - name: Clonar o repositório no host remoto para executar o script
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_remote_clone }}"
        version: "{{ repo_branch }}"
        force: yes

    - name: Verificar se o script instala_postinstall.sh existe
      stat:
        path: "{{ script_src_path }}"
      register: postinstall_check

    - name: Abortar se o script não for encontrado
      fail:
        msg: "O arquivo {{ script_filename }} não foi encontrado no repositório clonado: {{ script_src_path }}"
      when: not postinstall_check.stat.exists

    - name: Copiar o script para /tmp com permissão de execução
      copy:
        remote_src: true
        src: "{{ script_src_path }}"
        dest: "{{ script_dest_path }}"
        mode: '0755'

    - name: Verificar se o script foi copiado corretamente
      stat:
        path: "{{ script_dest_path }}"
      register: script_check

    - name: Abortar se o script não foi copiado corretamente
      fail:
        msg: "O script {{ script_filename }} não foi copiado corretamente para /tmp/"
      when: not script_check.stat.exists

    - name: Garantir permissão de execução no script
      file:
        path: "{{ script_dest_path }}"
        mode: '0755'

    - name: Executar o script instala_postinstall.sh
      command: "{{ script_dest_path }}"
      args:
        chdir: "/tmp"
